require "spec_helper"

feature "testing with teabag in the browser", js: true do

  before do
    Teabag.configuration.stub(:suites).and_return "integration" => proc{ |suite|
      suite.matcher = "spec/dummy/app/assets/javascripts/integration/*_spec.{js,js.coffee,coffee}"
      suite.helper = nil
    }
  end

  scenario "gives me the expected results" do
    visit "/teabag/integration?reporter=HTML"

    within("#teabag-progress") do
      expect(find("em")).to have_content("100%")
    end

    within("#teabag-stats") do
      expect(find("li:nth-child(1)")).to have_content("passes: 4")
      expect(find("li:nth-child(2)")).to have_content("failures: 1")
      expect(find("li:nth-child(3)")).to have_content("skipped: 1")
    end

    within("#teabag-report-failures") do
      expect(find("li.spec")).to have_content("Integration tests allows failing specs.")
    end

    expect(find("#spec_helper_el")).to have_content("this was generated by the spec_helper")
  end
end
